name: dungeons_and_music
description: "Music player application for Dungeons & Dragons sessions"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.4
  file_picker: ^10.1.9
  path_provider: ^2.1.2
  path: ^1.9.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  audio_session: ^0.2.2

  
  cupertino_icons: ^1.0.8
  dotted_border: ^3.0.1
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

 
  flutter_lints: ^6.0.0


flutter:

  
  uses-material-design: true
  
# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"  # Using a specific name for Android
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon/app_icon.png" # using the main icon as foreground too
  remove_alpha_ios: true
  web:
    generate: false


